site_name: NIMH Data Science & Sharing Team

theme: bootstrap4

plugins:
  - search
  - git-committers:
      repository: nimh-dsst/dsst-rtd
      branch: main
      # current 12/1/2023 fine-grained personal access token expires 12/1/2024
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - redirects:
      redirect_maps:
        about.md: https://cmn.nimh.nih.gov/dsst
        public.md: https://docs.google.com/spreadsheets/d/1t1VtW_ScMunEcrloxIv8197ezHQXCZQq_dxsSrH7SQI/edit?usp=sharing

docs_dir: docs

nav:
  - Welcome: index.md
  - About→: about.md
  - Datasets:
    - Curated IRP: curations.md
    - Publicly Available→: public.md
  - Tools: tools.md

  # please keep "Guides" alphabetical by first character
  - Guides:
    - ABCD Study Data: guides/abcd.md
    - DataLad New User FAQ: guides/datalad/faq.md
    - Enhanced NKI Rockland Sample Download: guides/downloads/enhanced-nki.md
    - GitHub Ownership Transfer: guides/github/transfer.md
    - NDA Tools Usage: guides/nda/downloadcmd.md
    - Trainings: guides/trainings.md

  - References: references.md
