site_name: NIMH Data Science & Sharing Team

theme: bootstrap4

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md

  - NIMH IRP Data Curations: curations.md

  - Available Public Datasets: public.md

  # please keep "Guides" alphabetical by first character
  - Guides:
    - DataLad New User FAQ: guides/datalad/faq.md
    - GitHub Ownership Transfer: guides/github/transfer.md
    - NDA Tools Usage: guides/nda/downloadcmd.md
    - Enhanced NKI Rockland Sample Download: downloads/enhanced-nki.md

  - References: references.md
