site_name: NIMH Data Science & Sharing Team

theme: bootstrap4

plugins:
  - search
  - git-committers:
      repository: nih-fmrif/dsst-rtd
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - redirects:
      redirect_maps:
        'about.md': 'https://cmn.nimh.nih.gov/dsst'

docs_dir: docs

nav:
  - Welcome: index.md
  - About: about.md
  - IRP Data Curations: curations.md
  - Available Public Datasets: public.md
  - Tools: tools.md

  # please keep "Guides" alphabetical by first character
  - Guides:
    - DataLad New User FAQ: guides/datalad/faq.md
    - Enhanced NKI Rockland Sample Download: guides/downloads/enhanced-nki.md
    - GitHub Ownership Transfer: guides/github/transfer.md
    - NDA Tools Usage: guides/nda/downloadcmd.md

  - References: references.md
